[package]
name = "wasm-net"
version = "0.1.0"
authors = [ "Denis Tsai <dt665m@gmail.com>", "Andrey Petrov <shazow@gmail.com>"]
description = "maybe libp2p-rs with wasm is better than js-libp2p"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
